<?php

namespace ContainerYERQtY6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportCsvCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ImportCsvCommand' shared autowired service.
     *
     * @return \App\Command\ImportCsvCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ImportCsvCommand.php';

        $container->privates['App\\Command\\ImportCsvCommand'] = $instance = new \App\Command\ImportCsvCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setName('app:import-csv');

        return $instance;
    }
}
