<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG4Oyt6L\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG4Oyt6L/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG4Oyt6L.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG4Oyt6L\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG4Oyt6L\App_KernelDevDebugContainer([
    'container.build_hash' => 'G4Oyt6L',
    'container.build_id' => 'bbf4bfc8',
    'container.build_time' => 1715642333,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG4Oyt6L');
