<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYERQtY6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYERQtY6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYERQtY6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYERQtY6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYERQtY6\App_KernelDevDebugContainer([
    'container.build_hash' => 'YERQtY6',
    'container.build_id' => '5f02b952',
    'container.build_time' => 1715692224,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYERQtY6');
